name: Build Facebook plug

on:
  push:
    tags:
      - 'facebook-v**'
    branches:
      - '**'
    paths:
      - 'build.sbt'
      - 'dataplug-facebook/**'
      - '.github/workflows/facebook.yml'

env:
  DATAPLUG: dataplug-facebook

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract Branch Name
        run:  |
          echo "BRANCH=$(echo ${GITHUB_REF})" >> $GITHUB_ENV

      - name: Display Branch Name
        run:  |
          echo "{{ $BRANCH }}"

      - name: Test 1
        if: contains(env.BRANCH, 'HOTFIX-deployment')
        run: |
          echo "Hello world"

      - name: Container Image Push - Master
        if: env.BRANCH == 'main'
        run: |
          docker tag hubofallthings/$DATAPLUG:$GITHUB_SHA hubofallthings/$DATAPLUG:main
          docker push hubofallthings/$DATAPLUG:main

      - name: Container Image Push - Tag
        if: contains(env.BRANCH, 'tags')
        run: |
         echo "Hello World"