name: Build Spotify plug

on:
  push:
    tags:
      - 'spotify-v**'
    branches:
      - '**'
    paths:
      - 'build.sbt'
      - 'dataplug-spotify/**'
      - '.github/workflows/spotify.yml'

env:
  DATAPLUG: dataplug-spotify

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Container Registry Login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Container Image Prepare
        run: sbt "project $DATAPLUG" docker:stage

      - name: Container Image Build
        run: docker build -t hubofallthings/$DATAPLUG:$GITHUB_SHA $DATAPLUG/target/docker/stage/

      - name: Container Image Push
        run: docker push hubofallthings/$DATAPLUG:$GITHUB_SHA

      - name: Container Image Push - Master
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          docker tag hubofallthings/$DATAPLUG:$GITHUB_SHA hubofallthings/$DATAPLUG:master
          docker push hubofallthings/$DATAPLUG:master

      - name: Container Image Push - Tag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker tag hubofallthings/$DATAPLUG:$GITHUB_SHA hubofallthings/$DATAPLUG:$(echo $GITHUB_REF | sed -e "s/refs\/tags\///g")
          docker push hubofallthings/$DATAPLUG:$(echo $GITHUB_REF | sed -e "s/refs\/tags\///g")
          docker tag hubofallthings/$DATAPLUG:$GITHUB_SHA hubofallthings/$DATAPLUG:latest
          docker push hubofallthings/$DATAPLUG:latest
